data:
    name: "ML1M"
    data_dir: "/DATA/"
    rating_threshold: 4
    drop_threshold: False
    apply_fillnan: True
    apply_preprocessing: True
    random_seed: 42
    hash_buckets:
        user_id: 3000
        item_id: 2000

features:
    numerical: ["freshness"]
    categorical: ["user_id", "item_id", "gender", "age", "occupation"]

optimizer: "SGD"
epochs: 100
random_seed: 42
lr: 0.01
model:
    dnn_hidden_units: [128, 128]
    embedding_dim: 32
    cross_num: 2
save_model_dir: ./output_model/
